basePath: /api/v1
host: http://localhost:8000
info:
  contact:
    email: jiangink.cn@gmail.com
    name: ink
    url: http://jiangink.github.com
  description: Market Monitor 简易API文档
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Market Monitor Swagger API
  version: "1.0"
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: 通过邮箱密码注册账号
      parameters:
      - description: 测试
        in: body
        name: test
        required: true
        schema:
          type: object
      - description: 邮箱账号
        in: body
        name: email
        required: true
        schema:
          type: object
      - description: 账号密码
        in: body
        name: accountPass
        required: true
        schema:
          type: object
      - description: 确认密码
        in: body
        name: confirmPass
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200, "code": 2000001, msg:"请求处理成功"}'
          schema:
            type: string
        "400":
          description: '{"status":400, "code": 4000003, msg:"注册密码不匹配"}'
          schema:
            type: string
        "500":
          description: '{"status":500, "code": 5000001, msg:"服务器内部错误"}'
          schema:
            type: string
      summary: 账号注册
      tags:
      - Auth
swagger: "2.0"
